[build]
  command = "npm run build:client"
  functions = "netlify/functions"
  publish = "dist"


[functions]
  node_bundler = "esbuild"
  
[[redirects]]
  force = true
  from = "/api/ping"
  status = 200
  to = "/.netlify/functions/ping"

[[redirects]]
  force = true
  from = "/api/contact"
  status = 200
  to = "/.netlify/functions/contact"

[[redirects]]
  force = true
  from = "/api/admin/login"
  status = 200
  to = "/.netlify/functions/admin-login"

[[redirects]]
  force = true
  from = "/api/admin/session"
  status = 200
  to = "/.netlify/functions/admin-session"

[[redirects]]
  force = true
  from = "/api/admin/logout"
  status = 200
  to = "/.netlify/functions/admin-logout"

[[redirects]]
  force = true
  from = "/api/admin/password"
  status = 200
  to = "/.netlify/functions/admin-password"
